apiVersion: v1
kind: Service
metadata:
  name: metricsdemo
  namespace: service-mesh
  labels:
    app: metricsdemo
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: metricsdemo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metricsdemo
  namespace: service-mesh
  labels:
    app: metricsdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metricsdemo
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: metricsdemo
        image: metricsdemo:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
